# REACTIVE NAVIGATION
# General evaluation / showcase configuration
# Developed by Luna Jimenez Fernandez
#
# This file contains all general parameters to be used while evaluating 
# or showcasing the trained agents.
# 
# In addition, the contents of this file are also used as a basis for the configuration
# used while training the agents. Training specific parameters can be found in the 
# method-specific files (such as reactive_pointnav_train.yaml)
#
# Finally, some of the parameters are specified via arguments during program launch:
#	- Agent type
#	- Dataset and splits to be used
#	- Path to pre-trained weights
#

ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000

SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    
  # Physics are explicitely disabled, to avoid segmentation faults
  HABITAT_SIM_V0:
    ENABLE_PHYSICS: False
    # PHYSICS_CONFIG_FILE: "None"
    

# DATASET: Data path, split and name are specified via argument
DATASET:
  TYPE: PointNav-v1
#  SPLIT: 
#  DATA_PATH:
#  NAME:

TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.3
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POSSIBLE_ACTIONS: ['STOP', 'MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'COLLISIONS']
  SUCCESS:
    SUCCESS_DISTANCE: 0.3

