# REACTIVE NAVIGATION
# Benchmark configuration
# Developed by Luna Jimenez Fernandez
#
# This file contains all general parameters to be used while benchmarking
# the agents
#
# In essence, this is a variation of the base file
# including some extra options (like Video output) to be used
# when evaluating the agents

# BENCHMARKING OPTIONS
VIDEO_OPTION: ["disk"]
VIDEO_DIR: "Evaluation/Reactive/Video"

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    
  # Physics are explicitely disabled, to avoid segmentation faults
  HABITAT_SIM_V0:
    ENABLE_PHYSICS: False
    
# DATASET: Data path, split and name are specified via argument
DATASET:
  TYPE: PointNav-v1
#  SPLIT: 
#  DATA_PATH:
#  NAME:

TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.3
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POSSIBLE_ACTIONS: ['STOP', 'MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', "TopDownMap", "COLLISIONS"]
  SUCCESS:
    SUCCESS_DISTANCE: 0.3

